name: stage_1
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  dio: ^4.0.4
  fl_chart: ^0.41.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_speed_dial: ^5.0.0+1
  font_awesome_flutter: ^9.2.0
  geolocator: ^9.0.0
  geolocator_android: ^4.0.0
  google_nav_bar: ^5.0.5
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  multi_select_flutter: ^4.0.0
  provider: ^6.0.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.9
  sqflite: ^2.0.0+4
  syncfusion_flutter_charts: ^19.3.57
  vn_provinces: ^0.0.2
  uuid: ^3.0.5
  webview_flutter: ^3.0.1
  permission_handler: ^10.0.0

dev_dependencies:
  build_runner: ^2.1.5

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:
    - family: avenirnext
      fonts:
        - asset: assets/fonts/AvenirNext-Regular.ttf
          weight: 300
        - asset: assets/fonts/AvenirNext-Medium.ttf
          weight: 600
